replicaCount: 1

image:
  repository: docker.io/library/devsu
  pullPolicy: IfNotPresent
  tag: "latest"
  requests:    
    cpu: 10m
    memory: 128Mi
  env:
    enabled: true
    configMaps:
      - name: WORK_ENVIRONMENT
        keyRef: work_environment
    secrets:
      - name: DATABASE_NAME
        keyRef: database_name
      - name: DATABASE_USER
        keyRef: database_user
      - name: DATABASE_PASSWORD
        keyRef: database_password


configMap:
  data:
    work_environment: helm

secret:
  data:
    database_name: Li9kZXZEb2NrZXIuc3FsaXRl
    database_user: ZGJVc2Vy
    database_password: ZGJQYXNz

probes:
  enabled: true
  liveness:
    path: /
    initialDelaySeconds: 20
    periodSeconds: 60
  readiness:
    path: /
    initialDelaySeconds: 5
    periodSeconds: 5
  startup:
    path: /
    failureThreshold: 3
    periodSeconds: 3

service:
  type: NodePort
  port: 8000
  nodePort: 30000

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
  # targetMemoryUtilizationPercentage: 50

ingress:
  enabled: true
  className: "nginx"
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: "devsu-test"
      paths:
        - path: /(.*)
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
