name: Deploy helm chart to EKS
description: 'Deploy helm chart to eks'
inputs:
  app_name:
    required: false
    default: ${{ github.repository }}
  helm_namespace:
    required: false
    default: default
  helm_chart_directory:
    required: true
  image:
    required: true
  image_tag:
    required: true
  execute_helm_test:
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - run: |
          helm upgrade --install -n ${{ inputs.helm_namespace }} --create-namespace ${{ inputs.app_name }} ${{ inputs.helm_chart_directory }} \
          --set image.repository=${{ inputs.image }} \
          --set image.tag=${{ inputs.image_tag }}
      shell: bash
    - run: sleep 10 && helm test ${{ inputs.app_name }} -n ${{ inputs.helm_namespace }}
      if: inputs.execute_helm_test
      shell: bash
