name: Node.js Package

on:
  #release:
  #  types: [created]
  pull_request:
    branches: [ main ]
  
env:
  NODE_VERSION: 18

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npx jest --coverage
      
  eslint:
    runs-on: ubuntu-latest
    needs: build-and-test     
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci
      - run: npx eslint .
      
  snyk:
    needs: eslint 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

